"""empty message

Revision ID: 09be39cf25bc
Revises: 161e0776595d
Create Date: 2023-01-04 12:35:01.519427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09be39cf25bc'
down_revision = '161e0776595d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notification_credentials_id_account_credentials'), 'account_credentials', ['credentials_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notification_credentials_id_account_credentials'), type_='foreignkey')
        batch_op.drop_column('credentials_id')

    # ### end Alembic commands ###
