"""empty message

Revision ID: 0d5494a80fba
Revises: 3034e6db891d
Create Date: 2022-12-18 04:33:37.618802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5494a80fba'
down_revision = '3034e6db891d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'account', ['account_owner_id'], ['account_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('account_owner_id')

    # ### end Alembic commands ###
