"""empty message

Revision ID: 0ebfd48b3deb
Revises: 8ec7a8212fb9
Create Date: 2023-01-04 12:13:32.565414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebfd48b3deb'
down_revision = '8ec7a8212fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('account_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('confirmation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    with op.batch_alter_table('confirmation', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    with op.batch_alter_table('account_credentials', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    # ### end Alembic commands ###
