"""empty message

Revision ID: 1654b8841290
Revises: 76075f0b1841
Create Date: 2022-12-21 08:16:47.338862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1654b8841290'
down_revision = '76075f0b1841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_credentials', schema=None) as batch_op:
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
