"""empty message

Revision ID: 18758742ad35
Revises: c35cec0bc048
Create Date: 2022-12-03 21:58:39.470057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18758742ad35'
down_revision = 'c35cec0bc048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.String(length=10), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('intent_message', sa.Boolean(), nullable=True),
    sa.Column('purchase_verification_message', sa.Boolean(), nullable=True),
    sa.Column('successful_purchase', sa.Boolean(), nullable=True),
    sa.Column('failed_purchase', sa.Boolean(), nullable=True),
    sa.Column('login_password', sa.String(length=120), nullable=True),
    sa.Column('login_email', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=10), nullable=True),
    sa.Column('seller_id', sa.String(length=10), nullable=True),
    sa.Column('account_id', sa.String(length=10), nullable=True),
    sa.Column('time_posted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('login_password', sa.VARCHAR(length=120), nullable=True),
    sa.Column('login_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('time_posted', sa.DATETIME(), nullable=True),
    sa.Column('buyer_id', sa.VARCHAR(length=10), nullable=True),
    sa.Column('type', sa.SMALLINT(), nullable=True),
    sa.Column('intent_message', sa.VARCHAR(length=120), nullable=True),
    sa.Column('purchase_verification_message', sa.VARCHAR(length=120), nullable=True),
    sa.Column('successful_purchase', sa.VARCHAR(length=120), nullable=True),
    sa.Column('failed_purchase', sa.VARCHAR(length=120), nullable=True),
    sa.Column('seller_id', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notification')
    # ### end Alembic commands ###
