"""empty message

Revision ID: 223e95ce6496
Revises: 6c6e2f0aa8d4
Create Date: 2022-12-25 19:45:14.982546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223e95ce6496'
down_revision = '6c6e2f0aa8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_complaint_account_id_account'), 'account', ['account_id'], ['account_id'], ondelete='CASCADE')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('account_owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_owner_id', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_complaint_account_id_account'), type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
