"""empty message

Revision ID: 45e21ce471c8
Revises: 7dfd1a9e8aba
Create Date: 2022-11-05 06:52:42.544353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e21ce471c8'
down_revision = '7dfd1a9e8aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
