"""empty message

Revision ID: 53a056c26bac
Revises: afff7831b637
Create Date: 2022-10-04 06:22:39.780705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a056c26bac'
down_revision = 'afff7831b637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_number', sa.Integer(), nullable=True))
        batch_op.drop_column('user_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_number', sa.INTEGER(), nullable=True))
        batch_op.drop_column('buyer_number')

    # ### end Alembic commands ###
