"""empty message

Revision ID: 6c6e2f0aa8d4
Revises: 1654b8841290
Create Date: 2022-12-21 09:30:23.218193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6e2f0aa8d4'
down_revision = '1654b8841290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('buyer_number')
        batch_op.drop_column('seller_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('buyer_number', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
