"""empty message

Revision ID: 79232946d8d1
Revises: 53a056c26bac
Create Date: 2022-10-06 08:34:29.992898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79232946d8d1'
down_revision = '53a056c26bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('buyer_id')

    # ### end Alembic commands ###
