"""empty message

Revision ID: 93bda19e5239
Revises: 18c17257c23c
Create Date: 2022-09-30 10:25:45.725992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bda19e5239'
down_revision = '18c17257c23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_password', sa.String(length=120), nullable=True),
    sa.Column('login_email', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.String(length=10), nullable=True),
    sa.Column('account_id', sa.String(length=10), nullable=True),
    sa.Column('time_posted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
