"""empty message

Revision ID: 9654b700ff08
Revises: 79232946d8d1
Create Date: 2022-10-13 13:29:06.161627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9654b700ff08'
down_revision = '79232946d8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmation_msg', sa.String(length=150), nullable=False),
    sa.Column('buyer_id', sa.String(length=120), nullable=True),
    sa.Column('buyer_email', sa.String(length=120), nullable=True),
    sa.Column('seller_id', sa.String(length=10), nullable=True),
    sa.Column('account_id', sa.String(length=10), nullable=True),
    sa.Column('time_posted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_msg')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation')
    # ### end Alembic commands ###
