"""empty message

Revision ID: afff7831b637
Revises: f68ba57aaec8
Create Date: 2022-10-04 06:19:16.719881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afff7831b637'
down_revision = 'f68ba57aaec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_number', sa.Integer(), nullable=True))
        batch_op.drop_column('user_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_number', sa.INTEGER(), nullable=True))
        batch_op.drop_column('buyer_number')

    # ### end Alembic commands ###
