"""added columns in message db

Revision ID: ca1a333f5e94
Revises: cb8a999e2004
Create Date: 2022-11-01 11:49:52.170123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1a333f5e94'
down_revision = 'cb8a999e2004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('intent_message', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('purchase_verification_message', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('successful_purchase', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('failed_purchase', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('failed_purchase')
        batch_op.drop_column('successful_purchase')
        batch_op.drop_column('purchase_verification_message')
        batch_op.drop_column('intent_message')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
