"""added columns in message db

Revision ID: cb8a999e2004
Revises: 9654b700ff08
Create Date: 2022-11-01 11:44:28.088120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8a999e2004'
down_revision = '9654b700ff08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('type', sa.SmallInteger(), nullable=False))
        batch_op.add_column(sa.Column('intent_message', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('purchase_verification_message', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('successful_purchase', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('failed_purchase', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('failed_purchase')
        batch_op.drop_column('successful_purchase')
        batch_op.drop_column('purchase_verification_message')
        batch_op.drop_column('intent_message')
        batch_op.drop_column('type')
        batch_op.drop_column('buyer_id')

    # ### end Alembic commands ###
