"""empty message

Revision ID: cddcf150e0a0
Revises: 587c36f58532
Create Date: 2022-12-14 23:38:51.119362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddcf150e0a0'
down_revision = '587c36f58532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('confirmation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rejected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_accepted', sa.Boolean(), nullable=True))
        batch_op.drop_column('if_rejected')
        batch_op.drop_column('if_accepted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('confirmation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('if_accepted', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('if_rejected', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_accepted')
        batch_op.drop_column('is_rejected')

    # ### end Alembic commands ###
