"""empty message

Revision ID: da713194d5f7
Revises: 93bda19e5239
Create Date: 2022-10-03 17:30:08.227817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da713194d5f7'
down_revision = '93bda19e5239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_number', sa.Integer(), nullable=True),
    sa.Column('seller_number', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('further_description', sa.String(length=250), nullable=True),
    sa.Column('time_posted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    # ### end Alembic commands ###
